name: 0.01.0$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/master
#trigger: none
trigger:
 branches:
   include:
     - main
 paths:
   include:
     - fusionCacheApi
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: 'windows-latest'
  workspace:
    clean: outputs 
 
  variables:
   buildPlatform: 'Any CPU'
   buildConfiguration: 'Release'    
   solution: 'fusionCacheApi.sln'
   project: 'fusionCacheApi/fusionCacheApi.csproj'
   redisccn:  $(redisconnectionstring)
  steps:
  - checkout: self
    clean: true

  # - script: |
  #    echo $(redisccn)

  - task: DotNetCoreCLI@2
    displayName: 'restore nuget'
    inputs:
      projects:  '$(solution)'
      command: 'restore'
      selectOrConfig: select

  

  - task: DotNetCoreCLI@2
    displayName: 'Build Project'
    inputs:
      command: build
      projects: $(project)
      arguments: '--configuration $(buildConfiguration)'


  - task: DotNetCoreCLI@2
    displayName: 'Publish and zip'
    inputs:
      command: publish
      publishWebProjects: False
      projects: $(project)
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'

  - task: AzureWebApp@1
    displayName: 'deploy to west-1'      
    inputs: 
      appType: 'webApp'
      appName: 'fusion-cache-api-west-1'
      azureSubscription: 'msc-dev-academy'
      package: '$(Build.ArtifactStagingDirectory)\fusionCacheApi'
      appSettings: -redis__connectionstring $(redisccn) 
      
  - task: AzureWebApp@1
    displayName: 'deploy to west-2'      
    inputs: 
      appType: 'webApp'
      appName: 'fusion-cache-api-west-2'
      azureSubscription: 'msc-dev-academy'
      package: '$(Build.ArtifactStagingDirectory)\fusionCacheApi'
      appSettings: -redis__connectionstring $(redisccn)


  - task: AzureWebApp@1
    displayName: 'deploy to north-1'      
    inputs: 
      appType: 'webApp'
      appName: 'fusion-cache-api-north-1'
      azureSubscription: 'msc-dev-academy'
      package: '$(Build.ArtifactStagingDirectory)\fusionCacheApi'
      appSettings: -redis__connectionstring $(redisccn)

        
  - task: AzureWebApp@1
    displayName: 'deploy to north-2'      
    inputs: 
        appType: 'webApp'
        appName: 'fusion-cache-api-north-2'
        azureSubscription: 'msc-dev-academy'
        package: '$(Build.ArtifactStagingDirectory)\fusionCacheApi'
        appSettings: -redis__connectionstring $(redisccn)

  